# https://dart.dev/tools/pub/pubspec
name: hotreloader
version: 1.0.0

description: Hot code reloader

repository: https://github.com/vegardit/dart-hotreloader
homepage: https://github.com/vegardit/dart-hotreloader
documentation: https://github.com/vegardit/dart-hotreloader/blob/master/README.md
issue_tracker: https://github.com/vegardit/dart-hotreloader/issues

environment:
  # https://dart.dev/tools/pub/pubspec#sdk-constraints
  sdk: '>=2.6.0 <3.0.0'

# https://dart.dev/tools/pub/dependencies#version-constraints
dependencies:
  logging: ^0.11.4         # https://pub.dev/packages/logging
  path: ^1.6.4             # https://pub.dev/packages/path
  stream_transform: ^1.1.0 # https://pub.dev/packages/stream_transform
  vm_service: ^4.0.0       # https://pub.dev/packages/vm_service
  watcher: ^0.9.7+14       # https://pub.dev/packages/watcher

dev_dependencies:
  lint: ^1.0.0
